/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinaled;
import PacoteCanvas.Canvas;
import PacoteCanvas.Retangulo;
import LSE.LSE;
import javax.swing.JOptionPane;

/**
 *
 * @author hellder
 */
public class TelaLSETEste extends javax.swing.JFrame {
    private Canvas canvas;
    private LSE lse;
    private Retangulo retangulo;
    int x, y;
    /**
     * Creates new form TelaLSETEste
     */
    public TelaLSETEste() {
        initComponents();      initComponents();
        canvas = new Canvas();
        canvas.setBounds(HEIGHT + 300, WIDTH + 5, 700, 700);
        this.add(canvas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAdicionarElemento = new javax.swing.JButton();
        jbRemoverElemento = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTamanho = new javax.swing.JLabel();
        lblElemRemovido = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        jbCriarLSE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbAdicionarElemento.setText("Adicionar Elemento");
        jbAdicionarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarElementoActionPerformed(evt);
            }
        });

        jbRemoverElemento.setText("Remover Elemento");
        jbRemoverElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverElementoActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar na lista");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da LSE"));

        lblTamanho.setText("Tamanho:");

        lblElemRemovido.setText("Elemento Removido:");

        lblInicio.setText("Inicio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamanho)
                    .addComponent(lblElemRemovido)
                    .addComponent(lblInicio))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblTamanho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblElemRemovido)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jbCriarLSE.setText("Criar LSE");
        jbCriarLSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarLSEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdicionarElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCriarLSE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRemoverElemento, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(436, 522, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCriarLSE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdicionarElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdicionarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarElementoActionPerformed

        if(lse.insere(lse.tamanho()+1, Integer.parseInt(JOptionPane.showInputDialog("Digite o valor a ser adicionado a lista")))){
            x=(x+70);
            retangulo = new Retangulo();
            retangulo.setCoordX(x);
            retangulo.setCoordY(y);
            retangulo.setValor(Integer.toString(lse.elemento(lse.tamanho())));
            retangulo.setBasePx(50);
            retangulo.setAlturaPx(25);
            
            
            canvas.adicionar(retangulo);
            retangulo.setValor(Integer.toString(lse.tamanho()+1));
            
            canvas.AddRepresentaFila(retangulo);
            canvas.PintaRepresentaLSE(canvas.getGraphics());
            canvas.paintFila(canvas.getGraphics());
            
            
            
            
            lblTamanho.setText(String.valueOf("Tamanho: "+lse.tamanho()));
 //           lblInicio.setText(String.valueOf("Incio:"+lse.elemento(lse.tamanho()+1)));
            lblElemRemovido.setText("Elemento Removido: null");
            
            
        } else {
            //exibe mensagem de erro;
            JOptionPane.showMessageDialog(null, "", "Falha na inserção do Elemento", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbAdicionarElementoActionPerformed

    private void jbRemoverElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverElementoActionPerformed

        if(!lse.vazia()){
            int aux,re;
            canvas.remover(lse.remove(re=Integer.parseInt(JOptionPane.showInputDialog("Qual a possição a ser removida?"))));
            aux= lse.remove(re);
            canvas.RemoveFilaCanvas();
            canvas.paintFila(canvas.getGraphics());
            x = x -70;
   
//            lblInicio.setText("Inicio: " + lse.elemento(aux));

 
//            lblTamanho.setText("Tamanho: " + lse.tamanho());

//            lblElemRemovido.setText("Elemento Removido: " + aux);

        } else {
            JOptionPane.showMessageDialog(null, "Posição invalida ou lista vazia.", "ERRO AO REMOVER ELEMENTO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbRemoverElementoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        //verifica se a fila está vazia;
        if (!lse.vazia()) {

            JOptionPane.showMessageDialog(null, "Elemento:" + lse.elemento(Integer.parseInt(JOptionPane.showInputDialog("Qual a possição?"))), "CONSULTA ELEMENTO", JOptionPane.INFORMATION_MESSAGE);
        } else {

            //exibe uma mensagem de erro se a pilha estiver vazia;
            JOptionPane.showMessageDialog(null, "A Lista está vazia ou a posição de pesquisa é invalida", "CONSULTA ELEMENTO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbCriarLSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarLSEActionPerformed
        if(canvas.Tamanho()==0){
            lse = new LSE();
            lblTamanho.setText("Tamanho: "+lse.tamanho());
            lblInicio.setText("Inicio "+ lse.posicao(0));
            lblElemRemovido.setText("Elemento Removido: null");
            x=0;
            y=50;
            retangulo = new Retangulo();
            
            
        } else {
            //exibe uma mensagem de erro;
            JOptionPane.showMessageDialog(null, "Uma estrutura já foi criada. Remova todos os elementos"
                + " da estrutura para criar outra !", "Criar outra Lista", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbCriarLSEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLSETEste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLSETEste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLSETEste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLSETEste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLSETEste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAdicionarElemento;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCriarLSE;
    private javax.swing.JButton jbRemoverElemento;
    private javax.swing.JLabel lblElemRemovido;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblTamanho;
    // End of variables declaration//GEN-END:variables

    private static class lblTamanho {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public lblTamanho() {
        }
    }
}
